import functools,http.server,json,threading
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).parent; server=http.server.ThreadingHTTPServer(('127.0.0.1',0),functools.partial(http.server.SimpleHTTPRequestHandler,directory=str(ROOT)));threading.Thread(target=server.serve_forever,daemon=True).start();base=f'http://127.0.0.1:{server.server_port}/';results=[]
with sync_playwright() as p:
 b=p.chromium.launch(headless=True,args=['--no-sandbox'])
 for w in (360,768,1280):
  page=b.new_page(viewport={'width':w,'height':900},reduced_motion='reduce');errs=[];external=[];page.on('pageerror',lambda e:errs.append(str(e)));page.on('request',lambda q:external.append(q.url) if not q.url.startswith(base) else None);page.goto(base);page.locator('#start').click();assert page.locator('h2').inner_text()=='Choose a creek team';page.locator('#check').click();assert 'Healthy model' in page.locator('#feedback').inner_text();page.screenshot(path=str(ROOT/f'evidence-habitat-{w}.png'),full_page=True);page.locator('[data-tab="predict"]').click();page.locator('.scenario').nth(1).click();page.locator('input[value=shrink]').check();page.locator('#step').click();assert 'Day 1' in page.locator('#readout').inner_text();page.screenshot(path=str(ROOT/f'evidence-predict-{w}.png'),full_page=True);page.locator('[data-tab="restore"]').click();page.locator('#water').fill('0');page.locator('#restorecheck').click();assert 'Try adding water' in page.locator('#restorefeedback').inner_text();page.locator('#water').fill('8');page.locator('#restorecheck').click();assert 'Repair works' in page.locator('#restorefeedback').inner_text();page.screenshot(path=str(ROOT/f'evidence-restore-{w}.png'),full_page=True);assert page.evaluate('document.documentElement.scrollWidth<=innerWidth');results.append({'viewport':f'{w}x900','browser':b.version,'page_errors':errs,'external_requests':external,'result':'pass'})
 b.close()
(ROOT/'browser-results.json').write_text(json.dumps(results,indent=2)+'\n');server.shutdown();print(json.dumps(results))
